apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-nginx
  namespace: default
  labels:
    name: c-nginx
spec:
  selector:
    matchLabels:
      app: c-nginx
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: c-nginx
    spec:
      containers:
      - name: c-nginx
        # Updata nginx image version => nginx:v1.14.0-5 => nginx:v1.14.0-6
        image: 192.168.212.12/qoo13149/nginx:v1.14.0-5
        #image: 192.168.212.12/qoo13149/nginx:v1.14.0-6
        resources:
          requests:
            cpu: "50m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginx-data
        hostPath:
         path: /usr/share/kubernetes-lemp/k8s/nginx/html/
      - name: nginx-conf
        hostPath:
         path: /usr/share/kubernetes-lemp/k8s/nginx/conf/
