apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: c-nginx
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10