kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysqlpv
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
