apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-fpm
  namespace: default
  labels:
    name: c-fpm
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: c-fpm
  template:
    metadata:
      labels:
        app: c-fpm
    spec:
      containers:
      - name: c-fpm
        image: 192.168.212.12/qoo13149/php-fpm:v7.3
        resources:
          requests:
            cpu: "50m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-data
        ports:
        - containerPort: 9000
      volumes:
      - name: nginx-data
        hostPath:
         path: /usr/share/kubernetes-lemp/k8s/nginx/html/